name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0,6" # Mondays & Saturday at 00:00

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          QUOTE=$(shuf -n 1 quotes.txt)
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ secrets.NAME }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "$QUOTE"
          git push
